### ISSUE TITLE
User Can Search For Books

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#1]
## 💰 Motivation
User should be able to search for Books.

## 📐 Plan
Allow user to search the Google Books API for any book in that database. User can search generally, or narrow their query to specify the title of a book, an author, or the ISBN.

## 🖼️ Wireframe
![Screen Shot 2021-04-05 at 3 52 18 PM](https://user-images.githubusercontent.com/74999873/113636357-3b6fb680-9627-11eb-8d5a-0115f184aee4.png) ![Screen Shot 2021-04-05 at 3 52 29 PM](https://user-images.githubusercontent.com/74999873/113636362-3e6aa700-9627-11eb-96d4-59564cf55ba3.png)
![Screen Shot 2021-04-05 at 3 53 19 PM](https://user-images.githubusercontent.com/74999873/113636365-40cd0100-9627-11eb-8065-105c44e5c12d.png)
![Screen Shot 2021-04-05 at 3 53 28 PM](https://user-images.githubusercontent.com/74999873/113636372-432f5b00-9627-11eb-9e8e-192b6928fa10.png)

## ✅ Task List

For main search page:
- [x] within a React class component return a form element
- [x] add input element to form and make required for submit
- [x] add a value to state to gather information typed into input
- [x] add a prop to this.state to identify which button is being clicked
- [x] add a submit function to handle the form submission
- [x] include event.preventDefault to submit function
- [x] add a change function to handle data submitted in input 
- [x] add buttons for submit and advanced search
- [x] add function to handle advanced search button
- [x] add colors to background, input and buttons
- [x] update fonts in CSS to reflect figma wireframe
- [x] update colors of fonts
- [x] ensure form looks good on mobile and desktop
- [x] add menu element to activate app drawer component
- [x] listen for clicks on submit and advanced search button
- [x] apply appropriate state changes for which element is clicked
- [x] query the google books api with fetch and data gathered from input
- [x] set up error handling for fetch request

For Advanced Search page:
- [x] Create a form element (possibly 3 separate forms?)
- [x] add 3 input areas for searching by title, author, ISBN
- [x] Add three submit buttons for each input area 
- [x] make each input area required for 
- [x] ensure form looks good on mobile and desktop
- [x] listen for clicks on submit buttons
- [x] query the google books api with data gathered from each input
