### ISSUE TITLE
User Can Delete Books 

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#10]
## 💰 Motivation
If the user mistakenly adds a book to their reading list - or decides they no longer want to read it - they should be able to remove it from their list.

## 📐 Plan
Give the user the option to delete an entry from their reading list.

## 🖼️ Wireframe
![Screen Shot 2021-04-05 at 4 58 00 PM](https://user-images.githubusercontent.com/74999873/113640362-1fbcde00-9630-11eb-8ebb-a7dbbe36bbca.png)
![Screen Shot 2021-04-05 at 4 57 39 PM](https://user-images.githubusercontent.com/74999873/113640368-2186a180-9630-11eb-99c1-1cb7c80a2e54.png)
![Screen Shot 2021-04-05 at 4 57 26 PM](https://user-images.githubusercontent.com/74999873/113640391-2cd9cd00-9630-11eb-8bea-efd641967c63.png)

## ✅ Task List

- [x] create modal for delete on library page
- [x] create modal for delete on reading list page
- [x] add buttons to modals for yes and no
- [x] add overlay to both pages  to be activated with modals
- [x] add app.delete function to index.js
- [x] add ability to choose between tables for delete
- [x] add event listener to library page
- [x] add event listener to reading list page
- [x] add fetch request to library page
- [x] add fetch request to reading list page
- [x] add button animations to library page
- [x] add button animations to reading list page
