### ISSUE TITLE
User Can View Additional Search Results

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#12]
## 💰 Motivation
The User should be able to view additional results if the result they are looking for does not appear in the initial page render.

## 📐 Plan
When the User Scrolls to the bottom of the page additional search results should appear

## ✅ Task List

- [x] change search query for google books API to fetch additional results
- [x] add function to initial rendering methods to only display first 10 results 
- [x] add function to display additional results when user goes to bottom of page
