### ISSUE TITLE
User Can See Results of Search

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#2]
## 💰 Motivation
User should be able to see the results of their search.

## 📐 Plan
Allow users to view a list of books that match their search.

## 🖼️ Wireframe
![Screen Shot 2021-04-05 at 4 07 02 PM](https://user-images.githubusercontent.com/74999873/113637254-ff3d5580-9628-11eb-86bc-3b19c6e70466.png)
![Screen Shot 2021-04-05 at 4 07 37 PM](https://user-images.githubusercontent.com/74999873/113637293-11b78f00-9629-11eb-8181-e27c3f55068d.png)

## ✅ Task List

- [x] Add Results Page
- [x] connect results page to search page on submit
- [x] connect results page to advanced search page on submit
- [x] add results to state in search & advanced search page
- [x] add results page to renderPage function in app.jsx
- [x] Add heading with menu icon on left side
- [x] ensure appdrawer opens and closes correctly on this page as well
- [x] create container for all search results
- [x] create cards for each individual result
- [x] from data gathered from api:
- [x]  Add book cover
- [x] add title
- [x] add author
- [x] add year of publication
- [x] add more info button
- [x] add icons to save books
- [x] add icons to add to reading list
- [x] add description of book to card
- [x] limit number of words that show up for description on card
- [x] add css to description to align with card in figma.
- [x] hide description of book for mobile view only
- [x] change header to reflect results 
- [x] ensure search results look good on both mobile and desktop
