### ISSUE TITLE
User Can Sign Up

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#24]
## 💰 Motivation
The User should be able to sign-up for an account that keeps track of their reading list and library.

## 📐 Plan
When the User opens the app they can sign up or sign in to access their own personal library and reading list

## ✅ Task List

- [x] add user to state in app and set to null
- [x] add isauthorizing to state and set to true
- [ ] create handlesign in function on app
- [ ] create handle signout function on app
- [ ] set contextvalue in app
- [ ] create home page with sign in/sign up features
- [ ] add modal to switch between sign in/sign up
- [ ] add text areas for username and password
- [ ] add submit button

https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions
