### ISSUE TITLE
Refactor Code: cleanup database organization

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#27]
## 📐 Plan
Simplify database by separating all book data into one table, with all user information in the next table

## ✅ Task List

- [x] update schema to reflect new tables
- [x] update app.post request to insert correct info into correct tables
- [x] update app.get request to get correct information from correct tables
- [x] update app.patch request to patch correct info
- [x] update app.delete to delete correct info
- [x] update handlesave in results.jsx
- [x] update handleadd in results.jsx
- [x] update handleadd in details.jsx
- [x] update handlesave in details.jsx
- [x] update componentdidmount in reading-list.jsx
- [x] update handledelete in reading-list.jsx
- [x] update componentDidMoutn in library.jsx
- [x] update handledelete in library.jsx
- [x] update handleclick in get-rating.jsx
