### ISSUE TITLE
User Can View Details

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#3]
## 💰 Motivation
If a user wants to find out more information about a particular book they should be able to view more details.

## 📐 Plan
Allow the user to choose a book from search results and view more information about it.

## 🖼️ Wireframe
<img width="189" alt="Screen Shot 2021-04-09 at 2 41 24 PM" src="https://user-images.githubusercontent.com/74999873/114243579-af6cd000-9941-11eb-8416-6faeee9b75bb.png">

![Screen Shot 2021-04-05 at 4 11 00 PM](https://user-images.githubusercontent.com/74999873/113637510-999d9900-9629-11eb-9158-6833a15157bf.png)

## ✅ Task List

- [x] add event handler to results page to be activated when user clicks 'more info' button
- [x] add all book data to value passed to more info page
- [x] create more info page
- [x] create container for info
- [x] add title, author, year, isbn, description, category from API to page
- [x] add book cover
- [x] size cover according to mobile/desktop
- [x] add description to both pages
- [x] add button to add to library
- [x] add button to add to reading list
- [x] change heading to 'more info'
- [x] restructure so fetch happens on details page
- [x] apply hash routing so 'back' and 'forward' buttons work 
- [x] ensure page looks good on mobile and desktop
