### ISSUE TITLE
User Can Save Books They Have Already Read

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#4]
## 💰 Motivation
If a user has read a book that is returned in the search results, they should be able to save that book into their own virtual library.

## 📐 Plan
Allow the user to save a book from the search results or from the more info page.

## 🖼️ Wireframe
![Screen Shot 2021-04-05 at 4 15 33 PM](https://user-images.githubusercontent.com/74999873/113637882-7cb59580-962a-11eb-9a32-3f1e7aa8d9db.png) ![Screen Shot 2021-04-05 at 4 15 23 PM](https://user-images.githubusercontent.com/74999873/113637883-7cb59580-962a-11eb-9ac6-c01dbcff8288.png)
![Screen Shot 2021-04-05 at 4 17 04 PM](https://user-images.githubusercontent.com/74999873/113637877-7a533b80-962a-11eb-96a7-bb9fdb2667d4.png)
![Screen Shot 2021-04-05 at 4 16 47 PM](https://user-images.githubusercontent.com/74999873/113637880-7b846880-962a-11eb-8e3f-71fb80b1499f.png)

## ✅ Task List

- [x] add event handler to results page
- [x] add prop to state to listen for clicks on results page
- [x] add event handler to details page
- [x] add prop to state to listen for clicks on details page.
- [x] add timer function to revert state back to false after several seconds to results page
- [x] add timer function to revert state back to false after several seconds to details page
- [x] build modal pop-up for results page
- [x] build modal pop-up for details page
- [x] add button animations for results click
- [x] add button animations for details click
- [x] set up database
- [x] set up table for 'library'
- [x] set up index.js to handle post request
- [x] add function to results page to insert data into library table in database
- [x] add function to details page to insert data into library table in databse
- [x] add error message if book already added to database
- [x] ensure buttons/pop-ups look good on mobile/dekstop
