### ISSUE TITLE
User Can View Library

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#5]
## 💰 Motivation
The user should be able to access a list of all books they have saved into their library of already read books. 

## 📐 Plan
Allow the user to view all saved books in a list that provides the ability to view more info 

## 🖼️ Wireframe
![Screen Shot 2021-04-05 at 4 20 50 PM](https://user-images.githubusercontent.com/74999873/113638099-e9c92b00-962a-11eb-8126-4d9449e74e2c.png)
![Screen Shot 2021-04-05 at 4 20 30 PM](https://user-images.githubusercontent.com/74999873/113638100-ea61c180-962a-11eb-98be-0db800350092.png)

## ✅ Task List

- [x] create library page
- [x] add page routing for library page
- [x] add container for page
- [x] add header for page
- [x] add app.get request to index.js
- [x] add function to library page to get info from library
- [x] add ability to click on card to send to details page
- [x] render information correctly on page
- [x] add cards for entries
- [x] add info to cards: title & author 
- [x] add cover image to cards
- [x] add icon to delete
- [x] add rating info + stars
- [x] style page to reflect figma
- [x] ensure it looks good on mobile/desktop
- [x] remove unnecessary css
- [x] remove console logs and commented out code
