### ISSUE TITLE
User Can Rate Books in Library

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#6]
## 💰 Motivation
The user should be able to keep track of how much they liked each book they've added to their library.

## 📐 Plan
Allow the user to rate each book in the library with one to five stars.

## 🖼️ Wireframe
![Screen Shot 2021-04-05 at 4 37 38 PM](https://user-images.githubusercontent.com/74999873/113639114-4c232b00-962d-11eb-9abf-420ebf7dd4c9.png)
![Screen Shot 2021-04-05 at 4 37 18 PM](https://user-images.githubusercontent.com/74999873/113639091-4299c300-962d-11eb-8445-8b034e3b377d.png)

## ✅ Task List

- [x] add ratings info to table
- [x] add function to listen for clicks on stars
- [x] add function to change classes from clear hearts to full hearts on click
- [x] add to library get request to render hearts in database
- [x] add patch request to update hearts on clicks in database
- [x] add fetch request in library page to update hearts in database on click
