### ISSUE TITLE
User Can Add to Reading List

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#7]
## 💰 Motivation
If the user discovers a book in the search results that they haven't read, but would like to, they should be able to add it to a reading list separate from their library.

## 📐 Plan
Give the user the option to add any book to a reading list from the search results or the book info page.

## 🖼️ Wireframe
![Screen Shot 2021-04-05 at 4 44 09 PM](https://user-images.githubusercontent.com/74999873/113639505-2d716400-962e-11eb-8f93-7924d59d590a.png) ![Screen Shot 2021-04-05 at 4 43 42 PM](https://user-images.githubusercontent.com/74999873/113639508-2e09fa80-962e-11eb-80dd-588f474094d7.png)
![Screen Shot 2021-04-05 at 4 42 34 PM](https://user-images.githubusercontent.com/74999873/113639528-36facc00-962e-11eb-81fd-c5313dc7149d.png)
![Screen Shot 2021-04-05 at 4 42 25 PM](https://user-images.githubusercontent.com/74999873/113639529-382bf900-962e-11eb-8e26-946d17cd32d2.png)

## ✅ Task List
- [x] add event handler to results page
- [x] add prop to state to listen for clicks on results page
- [x] add event handler to details page
- [x] add prop to state to listen for clicks on details page.
- [x] add timer function to revert state back to false after several seconds to results page
- [x] add timer function to revert state back to false after several seconds to details page
- [x] build modal pop-up for results page
- [x] build modal pop-up for details page
- [x] add button animations for results click
- [x] add button animations for details click
- [x] set up schema for reading list
- [x] set up table for 'reading list'
- [x] set up index.js to handle post request for reading list
- [x] add function to results page to insert data into reading list table in database
- [x] add function to details page to insert data into reading list table in databse
- [x] add error message if book already added to database
- [x] ensure buttons/pop-ups look good on mobile/dekstop
