### ISSUE TITLE
User Can View Reading List

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/Final-Project#8]
## 💰 Motivation
The user should be able the view all books added to the reading list. 

## 📐 Plan
Allow the user to view a list of all books added to the reading list.

## 🖼️ Wireframe
![Screen Shot 2021-04-05 at 4 45 38 PM](https://user-images.githubusercontent.com/74999873/113639703-9a84f980-962e-11eb-8079-f357058280d1.png)
![Screen Shot 2021-04-05 at 4 47 40 PM](https://user-images.githubusercontent.com/74999873/113639733-acff3300-962e-11eb-9607-4d4769e4b648.png)

## ✅ Task List

- [x] create reading-list page
- [x] add page routing for reading-list page
- [x] add container for page
- [x] add header for page
- [x] adjust app.get request on index.js to be able to use library and reading list
- [x] add function to reading-list page to get info from database
- [x] add ability to click on card to send to details page
- [x] render information correctly on page
- [x] add cards for entries
- [x] add info to cards: title & author 
- [x] add cover image to cards
- [x] add icon to delete
- [x] style page to reflect figma
- [x] ensure it looks good on mobile/desktop
- [ ] remove unnecessary css
- [ ] remove console logs and commented out code
